global using BuildingBlocks.CQRS.Command;
global using Ordering.Application.Data;
global using Ordering.Application.Dtos;
global using Ordering.Domain.Models;
global using Ordering.Domain.ValueObject;
global using Ordering.Application.Exceptions;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using Ordering.Domain.Events;